[workspace]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Mojo utility modules and CLI tools"
name = "mojo_scratch"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
format = "mojo format -l 102 ."
build-clr = "mojo build cli/clr-recent.mojo -o dist/clr-recent"
build-cdn = "mojo build cli/push-cdn.mojo -o dist/push-cdn"
build-here = "mojo build cli/here.mojo -o dist/here"
build-see = "mojo build cli/see.mojo -o dist/see"
build-isee = "mojo build cli/isee.mojo -o dist/isee -I modules"
build-all = { depends-on = [
  "build-clr",
  # "build-cdn",
  "build-here",
  "build-see",
  "build-isee",
] }
pack-fss = "mojo package modules/find_substring -o pack/find_substring.mojoc; cd pack; sha256sum find_substring.mojopkg > sha256sum.find_substring.mojopkg.txt"
pack-imencode = "mojo package modules/imencode -o pack/imencode.mojoc; cd pack; sha256sum imencode.mojopkg > sha256sum.imencode.mojopkg.txt"
pack-kitty = "mojo package modules/kitty_print -o pack/kitty_print.mojoc; cd pack; sha256sum kitty_print.mojopkg > sha256sum.kitty_print.mojopkg.txt"
install-bin = "cp ./dist/* ~/.local/bin"

[dependencies]
mojo = ">=1.0.0b1,<1.1"
